services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: orchestrator-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      GENERIC_TIMEZONE: "${GENERIC_TIMEZONE}"
      TZ: "${TZ}"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}"
      N8N_RUNNERS_ENABLED: "${N8N_RUNNERS_ENABLED}"
      N8N_PUBLIC_API_DISABLED: "false"
      N8N_ENABLE_API: "true"
      DB_TYPE: "${DB_TYPE}"
      DB_POSTGRESDB_DATABASE: "${DB_POSTGRESDB_DATABASE}"
      DB_POSTGRESDB_HOST: "${DB_POSTGRESDB_HOST}"
      DB_POSTGRESDB_PORT: "${DB_POSTGRESDB_PORT}"
      DB_POSTGRESDB_USER: "${DB_POSTGRESDB_USER}"
      DB_POSTGRESDB_SCHEMA: "${DB_POSTGRESDB_SCHEMA}"
      DB_POSTGRESDB_PASSWORD: "${DB_POSTGRESDB_PASSWORD}"
    volumes:
      - n8n_data:/home/node/.n8n
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_data:
    name: orchestrator-n8n-data
